### ISSUE TITLE
v1.1 release TODO

### ISSUE THREAD

**Issue by sergeche** [emmetio/emmet#284]
- [ ] docs about adding new Lorem Ipsum language, omitting common part
- [ ] docs about Can I Use
- [ ] “Match Tag” renamed to “Balance”, add demos
- [ ] New gradients (W3C specs, multiple definitions, Can I Use)
- [ ] How to write chained CSS abbrs in single line
- [ ] Slim & Jade syntaxes
- [ ] LESS and SCSS support
- [ ] New “Update Tag” action 
- [ ] Boolean attributes
- [ ] Implied & default attributes
- [ ] Multiple names in snippets definition
- [ ] CSS: add `.N` to produce rgba-values
- [ ] When wrapping URLs with `<a>`, it is automatically inserted into `href`
- [ ] Node.JS
##
